### ISSUE TITLE
Add prettier config

### ISSUE THREAD

**Issue by Dizeeee** [Dizeeee/dave#3]
We need a prettier config so we can enforce a basic style guide. I'm not super particular beyond using tabs and setting the max line length to 120 chars.

**Comment by piratekingdev** [comment]
I have started making a prettier configuration file as per the official documentation. I am just waiting to add this to the repository so I can do it in a separate PR. I'll continue to tweak and refine the configuration file until this time.

**Comment by piratekingdev** [comment]
I finished the prettier configuration file needed to resolve this issue. I added it to my initial PR. Once that PR is reviewed and allowed, this issue should be effectively closed.

The configuration file will enforce the following style rules:

* A default tab width of 4
* Enforce the use of tabs
* A maximum of 120 characters per line
* Enforce single quotes (ex: 'hello world')
* Enforce bracket spacing (ex: { 'example' })
* \n line endings. This will help resolve any formatting issues between Windows and Unix-like operating systems
